# Boltz configuration
seed: 68
recycling_steps: 3
diffusion_samples: 1
sampling_steps: 100
sampling_steps_affinity: 100
diffusion_samples_affinity: 3
affinity_mw_correction: true
output_format: "pdb"
override: true
no_kernels: true
remove_files: true # Remove files after processing

batch_predictions: true 

